### ISSUE TITLE
strong or weak augmentation have an ambiguity

### ISSUE THREAD

**Issue by nengwp** [Justherozen/ProMix#10]
on train_promin.py 
```
        # inputs_x: strong augmentation
        # inputs_x2: weak augmentation
```
Code comments and actual code execution are exactly opposite. What should be the correct one? Is the comment written wrong?

**Comment by nengwp** [comment]
Why input_x2 did not participate in subsequent network training?

**Comment by Justherozen** [comment]
Apologies for the minor issues in our comments. The `input_x` denotes weak augmentation, while `input_x2` denotes strong augmentation. The primary role of `input_x2` is to be involved in consistency regularization computations (in `loss_cr` and `loss_cr_2`).
