### ISSUE TITLE
CSS samples num in  imbalanced dataset

### ISSUE THREAD

**Issue by nengwp** [Justherozen/ProMix#11]
train_promix.py  at line 437:
```
    #class-wise small-loss selection (CSS for base selection set)
    losses = (losses - losses.min()) / (losses.max() - losses.min())
    all_loss.append(losses)
    input_loss = losses.reshape(-1, 1)
    prob = np.zeros(targets_list.shape[0])
    idx_chosen_sm = []
    min_len = 1e10
    for j in range(num_class):
        indices = np.where(targets_list.cpu().numpy()==j)[0]
        if len(indices) == 0:
            continue
        bs_j = targets_list.shape[0] * (1. / num_class)
        pseudo_loss_vec_j = losses[indices]
        sorted_idx_j = pseudo_loss_vec_j.sort()[1].cpu().numpy()
        partition_j = max(min(int(math.ceil(bs_j*rho)), len(indices)), 1)
        idx_chosen_sm.append(indices[sorted_idx_j[:partition_j]])
        min_len = min(min_len, partition_j)
    idx_chosen_sm = np.concatenate(idx_chosen_sm)
    prob[idx_chosen_sm] = 1
```

When the data set is extremely imbalanced, it seems unreasonable that this average selection exceeds the total number of minority classes.

> For example, if the number of categories is 100, 10, the average selection is 50*0.5=25,25>10.

How is this part set up in the category imbalance experiment?

**Comment by Justherozen** [comment]
Thanks for your question, the CSS process is different in the imbalanced scenario. where the code is as follows
```
bs_j = len(indices)
pseudo_loss_vec_j = losses[indices]
sorted_idx_j = pseudo_loss_vec_j.sort()[1].cpu().numpy()
partition_j = max(min(int(math.ceil(bs_j*rho)), len(indices)), 1)
```
Overall, there will be some differences in the category imbalance scenario. Feel free to reach out to me via email for more details.

**Comment by nengwp** [comment]
I didn't find your email address. Could you please give it to me? My email address is nengwp@qq.com
