### ISSUE TITLE
您觉得这个方法具备通用性吗？对于不同的分类任务/不同的分类模型而言。

### ISSUE THREAD

**Issue by Twsaiae** [Justherozen/ProMix#2]
我在寻找一种可以解决以下问题的方法：
因为人失误造成的错标，或者说模棱两可的数据标成任意一个类都可以，这样产生的数据集本身存在问题。

可是我的分类任务可能差异性并不是很明显，属于细颗粒度的分类，不像狗和茶杯这样的类别，而是OK和NG这样的判定，可能稍微有一点裂缝没啥问题，裂缝太大才有问题，稍微有一点缺失没问题，缺失很大才有问题，您的这个方法可以应用在我这个任务上吗？像我这种二分类是不是使用回归的方法效果更好哇，希望能得到您的回复。

**Comment by Twsaiae** [comment]
期待大佬回复的第一天。

**Comment by Twsaiae** [comment]
期待大佬回复的第二天。

**Comment by Twsaiae** [comment]
期待大佬回复的第三天。

**Comment by Justherozen** [comment]
> 我在寻找一种可以解决以下问题的方法： 因为人失误造成的错标，或者说模棱两可的数据标成任意一个类都可以，这样产生的数据集本身存在问题。
> 
> 可是我的分类任务可能差异性并不是很明显，属于细颗粒度的分类，不像狗和茶杯这样的类别，而是OK和NG这样的判定，可能稍微有一点裂缝没啥问题，裂缝太大才有问题，稍微有一点缺失没问题，缺失很大才有问题，您的这个方法可以应用在我这个任务上吗？像我这种二分类是不是使用回归的方法效果更好哇，希望能得到您的回复。

With my understanding, the problem you want to solve may be more related to Anomaly Detection in data mining. Anomaly detection aims to identify data that does not meet certain specifications, while the LNL problem studied by ProMix aims to detect those mislabeled data. Meanwhile, anomaly detection is mainly a binary classification problem, while LNL is a multi-class classification problem. The settings are somewhat different. We only verified the effect of promix under the LNL setting, but it may not be applicable to other settings as there is no free lunch.
As for fine-grained dataset, ProMix can achieve sota performance in our experiments on both the clothing1m dataset where all samples are clothes and the animal10n dataset where all samples are confusing animals. As for ambiguous data which can be annotated into any class, this may belong to the field of partial label learning in weakly-supervised learning. You can refer to our previous work pico and pico+: https://github.com/hbzju/PiCO . Hope this can help you!

**Comment by Twsaiae** [comment]
First of all,thank you very much for your reply.It is very helpful to me.I will study GitHub link you give.But there are some questions about your reply, is there any difference between the abnormal detection in the data mining and your Promix?Isn't it all through training a model,and then pick the error labels or outlier points.

**Comment by Twsaiae** [comment]
day n,emmmmmm.....looking forward to your reply.....is there any difference?

**Comment by Twsaiae** [comment]
Moreover,I tried your code on my own data set,the effect is worse than the result of training directly on one resnet model.I think that your code only needs half of the data+confidence>the confidence is greater than 0.99 data，which is too little.I want to adjust half to three quarters.Do you know which parameters might be useful for my situation?

**Comment by Justherozen** [comment]
> First of all,thank you very much for your reply.It is very helpful to me.I will study GitHub link you give.But there are some questions about your reply, is there any difference between the abnormal detection in the data mining and your Promix?Isn't it all through training a model,and then pick the error labels or outlier points.

> Moreover,I tried your code on my own data set,the effect is worse than the result of training directly on one resnet model.I think that your code only needs half of the data+confidence>the confidence is greater than 0.99 data，which is too little.I want to adjust half to three quarters.Do you know which parameters might be useful for my situation?

To the best of our knowledge, The detection of abnormal data and that of data with noisy labels are two different tasks. Anomaly detection is the task of training only on samples considered to be normal and identifying the abnormal test data with unexpected patterns (i.e., not fitting the normal data distribution), while the task of learning with noisy labels aims to obtain a noise-robust model with better performance. More concretely, data with corrupted annotation does not indicate it is abnormal, and vice versa. ProMix is designed for the LNL task and may not be applicable for anomaly detection.
As for the experimental setting, I am not sure whether ProMix can be directly adopted for the different settings of abnormal detection (which is not suggested). Besides, the initial selection ratio is set as 0.5 and can increase to 0.9 with matched high-confidence selection for the CIFAR-N dataset. For your own unknown dataset, all these parameters need to be re-tuned for performance improvement. You can adjust them as shown in the shell script. I hope this reply can clarify the unclear points and address your concerns.

**Comment by Twsaiae** [comment]
Thanks for your reply,I know where the difference is.
As for my test,the initial selection ratio is set as 0.75,but the result is worse than the result of training directly on one resnet18.I feel little sad, I try your demo, that's awosome,but for my project,it did not have great power.I don't know,this training method may not have a strategy to stop early?I will try to adjust the initial selection rate to 90 and add the early stop strategy.
I want to make your method more universal.Promix model is the combination of two resnet18, your method should be more suitable for competitions,for practical applications,I want to turn into one resnet and add an early stop strategy, also,open only one super parameter of the initial selection ratio.This will be more convenient to replace backbone.In this case,if it can work better than direct training,I will be very satisfied.

**Comment by billhhh** [comment]
@Twsaiae Hi, thanks for providing the discussion. Does it help on your dataset?

**Comment by ppsmk388** [comment]
@billhhh @Twsaiae 
I have encountered a similar problem, do you have any good solutions at present?
Thank you for sharing！
