### ISSUE TITLE
Hello, how to generate or download `CIFAR-10_human.pt`?

### ISSUE THREAD

**Issue by Nioolek** [Justherozen/ProMix#3]
Hello,  thank you for your nice work.
I want to know how to generate or download  `CIFAR-10_human.pt`?

**Comment by Justherozen** [comment]
Hello，the cifar-10_human.pt can be found in the github repo of CIFAR-N dataset: https://github.com/UCSC-REAL/cifar-10-100n

**Comment by Nioolek** [comment]
Thank you very much for your prompt reply
