### ISSUE TITLE
CIFAR100 is not running with the CIFAR-100_human.pt

### ISSUE THREAD

**Issue by ghoshsdeeep** [Justherozen/ProMix#9]
CIFAR10 seems to run but when I take CIFAR100 it gives this error?

Any idea.Is there any problem with the file 100_human.pt](https://github.com/UCSC-REAL/cifar-10-100n/blob/main/data/CIFAR-100_human.pt)
![Screenshot (124)](https://github.com/Justherozen/ProMix/assets/12712069/df33b74f-f1a8-401c-948d-66129e61cfe5)
![Screenshot (125)](https://github.com/Justherozen/ProMix/assets/12712069/9d7da872-e6ae-4174-aa97-038d5f0df047)

I see models are different

**Comment by Justherozen** [comment]
Thanks for your question! The noise type 'aggre_label' only exists in CIFAR-10N, while in CIFAR-100N there is only one general noise type 'noisy_label'. Please refer to https://github.com/UCSC-REAL/cifar-10-100n for more details.
